// app/ui/src/views/main/header.vue
<template>
    <div id="Header">
        <div id="navigation">
            <FontAwesomeIcon
                class="icon click transition"
                :icon="props.type == 'settings' ? faAngleLeft : faGear"
                @click="() => change(props.type == 'settings' ? 'sender' : 'settings')"
            />
            <span>
                {{ props.type != "settings" ? Locales.Settings : Locales.BackToHome }}
            </span>
        </div>
        <div id="switch" v-if="props.type != 'settings'">
            <div
                class="item click transition left"
                :id="props.type == 'sender' ? 'selected' : ''"
                @click="() => change('sender')"
            >
                <p>{{ Locales.Sender }}</p>
            </div>
            <div
                class="item click transition right"
                :id="props.type == 'receiver' ? 'selected' : ''"
                @click="() => change('receiver')"
            >
                <p>{{ Locales.Receiver }}</p>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import Locales from "@/locales";

import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { faGear, faAngleLeft } from "@fortawesome/free-solid-svg-icons";

const props = defineProps(["type"]);
const emit = defineEmits(["change"]);

function change(kind: string) {
    emit("change", kind);
}
</script>

<style scoped>
#Header {
    user-select: none;
    position: fixed;
    top: 20px;
    left: 20px;
    z-index: 10;
    display: flex;
}

#switch {
    background-color: #3951af;
    width: 212px;
    height: 44px;
    border-radius: 44px;
    position: relative;
    box-shadow: 0 4px 4px rgba(0, 0, 0, 0.25);
    margin-left: 300px;
}

#navigation .icon {
    color: #3951af;
    font-size: 17px;
}

#navigation span {
    color: #555;
    margin-left: 5px;
    position: relative;
    top: -2px;
}

#switch .item {
    width: 106px;
    height: 44px;
    border-radius: 44px;
}

#switch .item p {
    text-align: center;
    line-height: 44px;
}

#switch .left {
    position: absolute;
    left: 0;
}

#switch .right {
    position: absolute;
    right: 0;
}

#switch #selected {
    background-color: #829bff;
}

#switch #selected p {
    color: #fff;
}
</style>

// applications/shared/webview/src/widgets/header.tsx
import "../styles/header.css";

import { useRef } from "react";
import { useAtomValue } from "jotai";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGear, faAngleLeft } from "@fortawesome/free-solid-svg-icons";

import { localesAtom } from "../state";

export type Type = "settings" | "sender" | "receiver";

export default function ({ value, onChange }: { value: Type; onChange: (type: Type) => void }) {
    const locales = useAtomValue(localesAtom);
    const toggleRef = useRef<HTMLDivElement | null>(null);

    return (
        <>
            <div className='Header'>
                <div className='Navigation'>
                    <FontAwesomeIcon
                        className='icon click'
                        icon={value == "settings" ? faAngleLeft : faGear}
                        onClick={() => onChange(value == "settings" ? "sender" : "settings")}
                    />
                    <span>{value != "settings" ? locales.Settings : locales.BackToHome}</span>
                </div>
                <div
                    ref={toggleRef}
                    className='Toggle'
                    style={{
                        top: value == "settings" ? "-100px" : "0",
                    }}
                >
                    <div
                        id='slider'
                        style={{
                            left: value == "sender" ? 0 : "106px",
                        }}
                    ></div>
                    <div className='item click' onClick={() => onChange("sender")}>
                        <p
                            style={{
                                color:
                                    value == "sender" ? undefined : "var(--secondary-text-color)",
                            }}
                        >
                            {locales.Sender}
                        </p>
                    </div>
                    <div className='item click' onClick={() => onChange("receiver")}>
                        <p
                            style={{
                                color:
                                    value == "receiver" ? undefined : "var(--secondary-text-color)",
                            }}
                        >
                            {locales.Receiver}
                        </p>
                    </div>
                </div>
            </div>
        </>
    );
}
